name: Generate Keystore

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -keystore upload-keystore.jks -alias upload -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Triplens,O=Triplens,C=US"
          
          echo "========================================="
          echo "🔥 YOUR SHA-1 FINGERPRINT FOR FIREBASE: 🔥"
          keytool -list -v -keystore upload-keystore.jks -alias upload -storepass android -keypass android | grep "SHA1:"
          echo "========================================="

      - name: Upload Keystore as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-keystore
          path: upload-keystore.jks
