name: Generate Keystore

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate Keystore
        run: |
          # Generate the keystore
          keytool -genkeypair -v -keystore upload-keystore.jks -alias upload -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Triplens,O=Triplens,C=US"
          
          echo "========================================="
          echo "🔥 YOUR SHA-1 FINGERPRINT FOR FIREBASE: 🔥"
          keytool -list -v -keystore upload-keystore.jks -alias upload -storepass android -keypass android | grep "SHA1:"
          echo "========================================="
          
          echo "========================================="
          echo "🔐 YOUR BASE64 KEYSTORE SECRET (KEYSTORE_BASE64): 🔐"
          base64 -w 0 upload-keystore.jks
          echo ""
          echo "========================================="
